### ISSUE TITLE
Nested array of DTOs not working

### ISSUE THREAD

**Issue by rmsj** [spatie/data-transfer-object#102]
`class TagData extends DataTransferObject
{
    /** @var string */
   public $name;
}

class PostData extends DataTransferObject
{
    /** @var \TagData[] */
   public $tags;
}`

The code in the example doesn't work.
DTOs that have a nested array of DTOs failed with 
`Invalid type: expected `UserMetaData::organisations` to be of type `OrgMetaData[]`, instead got value `array`, which is array.

**Comment by brendt** [comment]
I'm pretty sure that the example you've provided isn't the one that's actually crashing? Have you used the full namespace as a type?

**Comment by brendt** [comment]
Closed since there hasn't been any followup

**Comment by rafalglowacz** [comment]
For anyone who runs into it like I just did:

It can happen when your array is keyed by strings instead of integers. In that case 
`\Spatie\DataTransferObject\ValueCaster::shouldBeCastToCollection`
will return false and you'll get the invalid type error.

The solution is to replace string keys with integers and put the string values in the nested DTOs instead. 

You could also manually build the array of nested DTOs in the parent DTO's constructor. This way you'll keep the string keys, but I guess that's kind of working around how this package handles things for you.
