### ISSUE TITLE
FQCN is not resolved in annotations

### ISSUE THREAD

**Issue by NoiseByNorthwest** [spatie/data-transfer-object#107]
Is it possible to add the support for non-FQCN in annotation ? It could be very useful in many cases, especially when the IDE itself automatically imports the non-local types.

**Comment by mfn** [comment]
Duplicate of https://github.com/spatie/data-transfer-object/issues/13 

Please see the linked PRs/issues, the TL;DR it's a complexity and performance thing, as there's no trivial way to get the FQCN without adding complexity/overhead.

Doesn't mean a good PR won't get attention :)

**Comment by brendt** [comment]
Personally I wouldn't consider adding this anymore:

- PHP 7.4 types make most docblocks redundant
- Using a proper IDE will auto import FQDNs
- Doccomment conventions state that FQDNs should always be used
- It's a performance nightmare to properly support non-FQDNs, because use statements are not accessible in reflection

**Comment by mfn** [comment]
>     * because use statements are not accessible in reflection

I wonder if https://wiki.php.net/rfc/attributes_v2 can change the game here
