### ISSUE TITLE
Mapping property names and nested Data

### ISSUE THREAD

**Issue by krizzdev** [spatie/data-transfer-object#142]
Thanks for the great package.
Is there a way to use automatic casting with other property names?
And how can I do that with nested DTO's

Example:

API sends:
```
[
     "order_id" => "2000000008",
     "order_date" => "2020-09-04 13:03:44",
     ...
     "customer" => [
         ...
       "display_name" => null,
       "is_guest" => "1",
     ],
     "items" => [
       [
         "order_item_id" => "55",
         "item_id" => "4",
         "external_name" => "Example Item Name",
         "quantity" => 1.0,
       ],
     ],
]
```

OrderData:

```
public static function fromRequest(OrderCreateRequest $request): self
    {
        return new self([
            'orderId' => $request->input('order_id'),
            'orderDate' => $request->input('order_date'),
            'orderedAt' => $request->input('ordered_at'),
            'customer' => CustomerData::fromArray($request->input('customer')),
            'items' =>...,
        ]);
    }
```

Currently I have added another static method to the Customer DTO:

```
public static function fromArray(array $data): self
    {
        return new self([
            'companyName' => Arr::get($data, 'display_name'),
            'isGuest' => Arr::get($data, 'is_guest'),
            
        ]);
    }
```

because I need to rename some properties from the external data.

Now I'm struggling with the items because the Order Data can have multiple Item DTO's:

```
/** @var \App\DataTransferObjects\ItemData[] */
    public $items;
```

And inside of this item DTO I have to rename some properties, too.

My goal is to put the whole content from the external data into the OrderData DTO and everything gets mapped.

Do you have some ideas or hints?

Kind regards
Chris

**Comment by mfn** [comment]
Seems easiest to map the names from the API as is first into the DTOs and then use some other means?

**Comment by mfn** [comment]
Yes, that's what I'm basically saying.

The goal of the DTO is to map 1:1 to the payload.

Of course you can use the constructor and _change_ the things the way you see fit. For example there APIs have json keys like `foo:bar:baz` which won't work without that.

But otherwise I would not bother much and transform this _outside_ the DTO.

The philosophy of this library is to be lean and not contain bells & whistles, but do one job and do it well. That's also the reason that, besides type checking/enforcement, there's no real "validation" of any kind included => separate concern.

**Comment by krizzdev** [comment]
Okay thanks for your explanation. I appreciate that :) Then I will go for the 1:1 names and do the renaming on the Action level. Thank you.
