### ISSUE TITLE
Collection in v3

### ISSUE THREAD

**Issue by jamesRUS52** [spatie/data-transfer-object#181]
Hello

How should I use collection in v3 ?

```
$dto = new MyDTO(
    collection: [ // This will become an object of class OtherDTOCollection
        ['id' => 1],
        ['id' => 2], // Each ite will be an instance of OtherDTO
        ['id' => 3],
    ],
    otherDTO: ['id' => 5], // This data will be cast to OtherDTO
);
```

Can you give me example of OtherDTOCollection class ?

**Comment by mariomka** [comment]
See #180

**Comment by sidigi** [comment]
Make example in docs) Otherwise many people will ask about it)

**Comment by brendt** [comment]
Feel free to send a PR to the README

**Comment by jamesRUS52** [comment]
It's not clear at all. Improve the docs and tests with collections pls.
It's too hard to migrate to v3, I have to change signature in all methods with SomeCollectionDTO to array and use psalm to validate it?

**Comment by brendt** [comment]
James, v2 and v3 are by no means meant to be compatible. It's a complete redesign of the package and it's not expected to be an easy upgrade path. That's why we're still supporting v2 in a separate branch. Please read about how this new version came to be here: https://github.com/spatie/data-transfer-object/issues/151 and read more discussion here: https://github.com/spatie/data-transfer-object/pull/159

Telling me to do things without having read up on the context of v3 doesn't help your case. I realise you might be in a frustrating spot if you want to update, but it was never the intention of this package of doing so.
