### ISSUE TITLE
MapFrom bugs

### ISSUE THREAD

**Issue by princejohnsantillan** [spatie/data-transfer-object#229]
**I can't use a root more than once.**

`user.email` returns null here
![Screen Shot 2021-08-20 at 4 19 30 AM](https://user-images.githubusercontent.com/60916966/130138895-53480a91-b542-4e79-a900-6882178b9268.png)

If I switch up the order then `user.name` returns null
![Screen Shot 2021-08-20 at 4 29 29 AM](https://user-images.githubusercontent.com/60916966/130139551-9231e3f6-2b5b-427f-b562-b733fc372e72.png)

**Sequence of properties matter?**

This works because `$description` is in the right order.
![Screen Shot 2021-08-20 at 4 23 49 AM](https://user-images.githubusercontent.com/60916966/130139300-5ec2520a-dd46-40fb-9743-24fb91823571.png)

This does not work because I moved it down?
![Screen Shot 2021-08-20 at 4 31 34 AM](https://user-images.githubusercontent.com/60916966/130139807-5886a6af-c6b1-4ed8-9492-8380adf3d346.png)

**Comment by brendt** [comment]
I'll look at this next week

**Comment by regnerisch** [comment]
I think this is a problem related to `Arr::forget` in `DataTransferObject` (https://github.com/spatie/data-transfer-object/blob/master/src/DataTransferObject.php#L30)

I have a similar bug:

```php
class ExampleData extends DataTransferObject
{
    #[CastWith(ModelCaster::class, Subscription::class)]
    public ?Collection $subscriptions;

    #[MapFrom('subscriptions.0')]
    public $subscription;
}
```

As `subscriptions` is coming first, it will be read from the DTO and `Arr::forget` will remove it. So if I try to access `subscriptions.0` it will not find the `subscriptions` key and no value will be passed. 

I'm pretty sure this is not the expected behaviour. `Arr::forget` must be removed and the `UnknownProperties`-Exception must be implemented another way. It seems as an easy solution to determine if unknown properties exists, or not.

**Comment by brendt** [comment]
Fixed in https://github.com/spatie/data-transfer-object/releases/tag/3.6.2

**Comment by princejohnsantillan** [comment]
Cool beans! Thanks @MaximeWillinger @shadowhand @brendt!
