### ISSUE TITLE
Call to undefined method `getFieldValidators`

### ISSUE THREAD

**Issue by kd-at-mi** [spatie/data-transfer-object#270]
I am upgrading a project to laravel 9 and the spatie/data-transfer-object package along with it.  After upgrading the getFieldValidators function is no longer working and I was hoping someone could point me in the right direction.  I have gone through some of the changelogs and old code and am lost.

Thanks for the help, I hope I put this in the right spot because I had no clue where to ask this question!

**Comment by aidan-casey** [comment]
@kd-at-mi - Are you getting an error at all?

**Comment by kd-at-mi** [comment]
Its showing up in my tests...

  Call to undefined method App\Objects\Context\Context::getFieldValidators()

This upgrade has been intense.  I basically renamed the FlexibleDataTransferObject to DataTransferObject and proceeded with the tests but it seems there are tons of errors relating to the DTO and even contracts

**Comment by aidan-casey** [comment]
@kd-at-mi - I assume you are trying to upgrade from v2 of this package to v3? You should not be renaming any files, but simply install the latest major version using composer.

To do this:

```sh
composer remove spatie/data-transfer-object && composer require spatie/data-transfer-object ^3
```

Ensure that you are not making use of the `getFieldValidators` method yourself, since it was removed in version 3. Also note that `FlexibleDataTransferObject` is not part of version 3.
