### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by princejohnsantillan** [spatie/data-transfer-object#284]
Add uncast method to Caster.

Example DateTimeZoneCaster:

```php
class DateTimeZoneCaster implements Caster
{   
    public function cast(string $value): DateTimeZone
    {
        return new DateTimeZone($value);
    }

    public function uncast(DateTimeZone $value): string
    {
        return $value->getName();
    }
}
```

So when I do a toArray it does not give me a serialized DateTimeZone object but a timezone string. This also properly defines the inverse of my cast.

**Comment by aidan-casey** [comment]
Hey @princejohnsantillan, thanks for the suggestion! Generally speaking, I do tend to agree that we should work toward this being supported because it has to do with serialization and deserialization. That said, I think that implementing "uncasting" into the current version of the package would be a little messy and hard to maintain. We will look to bring this in the next version of this package.
